import React, { useState } from 'react';
import Head from 'next/head';
import toast, { Toaster } from 'react-hot-toast';
import BackgroundImage from '../components/common/BackgroundImage';
import Hero from '../components/home/Hero';
import ResultsDisplay from '../components/home/ResultsDisplay';

export default function Home() {
  const [bookData, setBookData] = useState(null);

  const displayToast = (action) => {
    toast(action === 'add' ? 'Added to bookshelf' : 'Removed from bookshelf', {
      duration: 1500,
      position: 'bottom-left',
      icon: action === 'add' ? '📗' : '📕',
      style: {
        backgroundColor: '#2f2f2f',
        color: 'white',
        fontFamily: 'Inter',
      },
    });
  };

  return (
    <>
      <Head>
        <title>novelty</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.svg' />
      </Head>
      <BackgroundImage image={'img/home-bg.jpg'} />
      <Toaster />
      <div className='container mx-auto pt-28 pb-16 flex flex-col gap-14'>
        <Hero setBookData={setBookData} />
        <ResultsDisplay bookData={bookData} displayToast={displayToast} />
      </div>
    </>
  );
}
