import React, { useState } from 'react';
import Head from 'next/head';
import toast, { Toaster } from 'react-hot-toast';
import Hero from '../components/home/Hero';

export default function Home() {
  const displayToast = (action) => {
    toast(action === 'add' ? 'Added to bookshelf' : 'Removed from bookshelf', {
      duration: 1500,
      position: 'bottom-left',
      icon: action === 'add' ? '📗' : '📕',
      style: {
        backgroundColor: '#2f2f2f',
        color: 'white',
        fontFamily: 'Inter',
      },
    });
  };

  return (
    <>
      <Head>
        <title>novelty</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.svg' />
      </Head>
      <Toaster />
      <Hero />
    </>
  );
}
