import Head from 'next/head';
import Hero from '../components/home/Hero';

export default function Home() {
  return (
    <>
      <Head>
        <title>novelty</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.svg' />
      </Head>
      <Hero />
    </>
  );
}
